# The isoseq reference under investigation
species: Cyanea_sp
transcriptome: W7.clustered.hq.fasta

# Path to directory containing proteomes for all the other species
proteomes: /gpfs/ycga/work/dunn/cwd7/databases/proteomes_cnidaria

# Treeinform branch length thresholds
thresholds: [0,0.5,1,2,3,4,5,8,10,15,20,25]

# Databases
busco: /gpfs/gibbs/data/db/busco
diamond: /gpfs/ycga/work/dunn/cwd7/databases/diamond/nr

